name: Build and deploy Node.js app to Azure Web App - MyOrgWallet-Wallet-Node-Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Use 20.x per your `package.json`

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r server.js package.json package-lock.json dist/ deploy/
          # Add other directories like public/, or src/ if needed
          zip -r release.zip deploy

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C9451C0B762749E88DB6D686279FF2BD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ED19A14E83FD4E50BA73F4C96D8D5885 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF2CF21BA34844819EDFCD6D904B20D4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyOrgWallet-Wallet-Node-Server'
          slot-name: 'Production'
          package: ./deploy
